name: Validate JSON Files

on:
  push:
    paths:
      - '**/*.json'
      - '.github/workflows/validate-json.yml'
  pull_request:
    paths:
      - '**/*.json'
      - '.github/workflows/validate-json.yml'

jobs:
  validate_filter_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install check-jsonschema
        run: pip install check-jsonschema

      - name: Download Current Filter Schema
        run: |
          curl -o schema.json https://raw.githubusercontent.com/Kaqemeex/loot-filters-ui/refs/heads/main/schema.json

      - name: Validate JSON files
        run: |
          find . -type f -name "*.json" -not -path "./schema.json" -print0 | while IFS= read -r -d '' file; do
            echo "Validating $file..."
            if ! check-jsonschema --schemafile schema.json "$file"; then
              echo "‚ùå Validation failed for $file"
              exit 1
            fi
          done 